# Generated by Django 6.0.6 on 2026-08-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='order_status',
        ),
    ]
