# Generated by Django 6.0.6 on 2026-06-30 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent_id', 'name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
